#!/bin/sh
# Inherit vars
. ~/.shellprofile
export PATH="$HOME/.ashdwm/scripts:$PATH"

# ENV Vars
export QT_QPA_PLATFORM="xcb"
export QT_QPA_PLATFORMTHEME="qt6ct"
export XDG_CURRENT_DESKTOP=LXQt
export XDG_MENU_PREFIX=lxqt-

setxkbmap us &
~/.ashdwm/autostart.sh

while :; do
    dbus-run-session dwm 2> ~/.dwm.log || break
done
