#!/bin/bash

# update bg
feh --bg-fill $(cat ~/.cache/wal/wal) &

# update dwm
xdotool key --clearmodifiers super+control+shift+q

# update qutebrowser colors
~/.config/scripts/qute-reload &

# update emacs colors
emacsclient -e '(my/reload-xresources-theme)' &

# update firefox colors
pywalfox update &

# update kitty colors
pkill -SIGUSR1 kitty
